import {Component, OnInit} from '@angular/core';
import { UserService } from './user-service';
import { User } from './user';

@Component({
    selector: 'user-app',
    templateUrl: 'user.component.html'
})

export class UserComponent implements OnInit {

    users: User[];
    currentUser: User;
    currentUserId: number;
    userForm: User;

    constructor(private userService: UserService){
        this.users = [];
        this.currentUser = new User;
        this.currentUserId = 0;
        this.userForm = new User;
    }

    ngOnInit(): void {
        this.userService.getUsers().subscribe((data: User[])=>{
            console.log(data);
            this.users = data;
        })
    }

    onSubmitAdd(addUserForm: any)
    {
        this.currentUser.id = this.currentUserId; // initialized as 0 since autogenerated on backend;
        this.currentUser.name = addUserForm.value.name;
        this.currentUser.username = addUserForm.value.username;
        this.currentUser.password = addUserForm.value.password;
        this.currentUser.email = addUserForm.value.email;
        this.currentUser.userType = "user"; // default setting as type user when account is created
        console.log(addUserForm.value);

        this.userService.addUser(this.currentUser).subscribe();
    }

    refresh()
    {
        window.location.reload();
    }

    resetForm()
    {
        this.userForm = new User();
    } 

} 
